#!/bin/bash

# The purpose of this script is to make changes into files generated by
# 'yarn create react-app' after 'build' is run.
# 1. Move files to a new directory called 'user'
#    The resulting structure is 'build/user/static/<etc>'
# 2. Update reference on generated files from

help()
{
   echo ""
   echo "Usage: $0 -f folder_name"
   echo -e "\t-f Folder name"
   exit 1 # Exit script after printing help
}

while getopts "f:s:t:" opt
do
   case "$opt" in
      f ) folder_name="$OPTARG" ;;
      ?  ) help ;; # Print helpFunction in case parameter is non-existent
   esac
done


if [ -z "$folder_name" ]
then
   echo "Some or all of the parameters are empty";
   helpFunction
fi


echo "Create application folder: $folder_name"
mkdir -p $folder_name
cp -rf build/* $folder_name

#Change favicon url
find $folder_name"/index.html" -type f | xargs sed -i 's/\/favicon.ico/{{ STATIC_URL }}mfview\/favicon.ico/g'
find $folder_name"/index.html" -type f | xargs sed -i 's/\/static\/js/{{ STATIC_URL }}mfview\/static\/js/g'
find $folder_name"/index.html" -type f | xargs sed -i 's/\/static\/css/{{ STATIC_URL }}mfview\/static\/css/g'

find mfview/static/js/ -type f | xargs sed -i 's/static\/media/static\/mfview\/static\/media/g'
find mfview/static/css/ -type f | xargs sed -i 's/static\/media/static\/mfview\/static\/media/g'

find mfview/static/js/ -type f | xargs sed -i 's/logo.753248ba.png/logo.png/g'

cp src/assets/images/*.png mfview/static/media/